name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  base-path:
    description: The base ref to compare against.
    required: false
  current-path:
    description: The current ref to compare against.
    required: false

# Define your outputs here.
outputs:
  current-js:
    description: The current js.
  current-css:
    description: The current css.
  current-js-gz:
    description: The current js gzipped.
  current-css-gz:
    description: The current css gzipped.

runs:
  using: node24
  main: dist/index.js
