name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current
        id: checkout_current
        uses: actions/checkout@v6
        with:
          path: current

      - name: Checkout Base
        id: checkout_base
        uses: actions/checkout@v6
        with:
          path: base

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          base-path: base/__tests__/mocks
          current-path: current/__tests__/mocks

      - name: Print Output
        run: |
          echo "Current CSS: ${{ steps.test-action.outputs.current-css }}"
          echo "Base CSS: ${{ steps.test-action.outputs.base-css }}"
          echo "Current JS: ${{ steps.test-action.outputs.current-js }}"
          echo "Base JS: ${{ steps.test-action.outputs.base-js }}"
